import type { PackageListItem } from "./packageApi";

const NOW = Date.parse("2026-08-01T00:00:00.000Z");

export const COMPOSIO_CONNECTORS: PackageListItem[] = [
  {
    name: "composio-slack",
    displayName: "Composio Slack Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Slack agent messaging, channels, and workspace actions.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 30,
    updatedAt: NOW - 3600000 * 2,
    latestVersion: "1.0.0",
    categories: ["chat", "collaboration"],
    topics: ["slack", "messaging", "chat-ops", "composio"],
    verificationTier: "structural",
    stats: { downloads: 1240, installs: 412, stars: 98, versions: 3 },
  },
  {
    name: "composio-linear",
    displayName: "Composio Linear Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Linear issue tracking, project updates, and cycles.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 28,
    updatedAt: NOW - 3600000 * 4,
    latestVersion: "1.0.0",
    categories: ["docs", "productivity"],
    topics: ["linear", "issue-tracking", "project-management", "composio"],
    verificationTier: "structural",
    stats: { downloads: 980, installs: 310, stars: 74, versions: 2 },
  },
  {
    name: "composio-notion",
    displayName: "Composio Notion Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Notion workspace databases, pages, and knowledge bases.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 25,
    updatedAt: NOW - 3600000 * 6,
    latestVersion: "1.0.0",
    categories: ["docs", "productivity"],
    topics: ["notion", "databases", "knowledge-base", "composio"],
    verificationTier: "structural",
    stats: { downloads: 1150, installs: 385, stars: 89, versions: 3 },
  },
  {
    name: "composio-github",
    displayName: "Composio GitHub Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for GitHub repositories, pull requests, issues, and code reviews.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 24,
    updatedAt: NOW - 3600000 * 1,
    latestVersion: "1.0.0",
    categories: ["dev", "collaboration"],
    topics: ["github", "pull-requests", "devops", "composio"],
    verificationTier: "structural",
    stats: { downloads: 1620, installs: 530, stars: 124, versions: 4 },
  },
  {
    name: "composio-gmail",
    displayName: "Composio Gmail Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Gmail email searching, message drafting, and sending.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 22,
    updatedAt: NOW - 3600000 * 8,
    latestVersion: "1.0.0",
    categories: ["productivity", "communication"],
    topics: ["gmail", "email", "google", "composio"],
    verificationTier: "structural",
    stats: { downloads: 890, installs: 290, stars: 65, versions: 2 },
  },
  {
    name: "composio-jira",
    displayName: "Composio Jira Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Jira software tickets, sprints, and project boards.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 20,
    updatedAt: NOW - 3600000 * 12,
    latestVersion: "1.0.0",
    categories: ["productivity", "dev"],
    topics: ["jira", "agile", "atlassian", "composio"],
    verificationTier: "structural",
    stats: { downloads: 740, installs: 245, stars: 52, versions: 2 },
  },
  {
    name: "composio-trello",
    displayName: "Composio Trello Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary: "Composio open-source connector for Trello boards, cards, and list management.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 18,
    updatedAt: NOW - 3600000 * 14,
    latestVersion: "1.0.0",
    categories: ["productivity"],
    topics: ["trello", "kanban", "composio"],
    verificationTier: "structural",
    stats: { downloads: 520, installs: 175, stars: 38, versions: 1 },
  },
  {
    name: "composio-supabase",
    displayName: "Composio Supabase Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary: "Composio open-source connector for Supabase SQL database queries, storage, and Auth.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 16,
    updatedAt: NOW - 3600000 * 5,
    latestVersion: "1.0.0",
    categories: ["dev", "cloud"],
    topics: ["supabase", "postgres", "database", "composio"],
    verificationTier: "structural",
    stats: { downloads: 1040, installs: 350, stars: 82, versions: 3 },
  },
  {
    name: "composio-discord",
    displayName: "Composio Discord Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Discord bot interactions, webhooks, and guild channels.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 14,
    updatedAt: NOW - 3600000 * 9,
    latestVersion: "1.0.0",
    categories: ["chat", "community"],
    topics: ["discord", "bot", "webhooks", "composio"],
    verificationTier: "structural",
    stats: { downloads: 830, installs: 270, stars: 61, versions: 2 },
  },
  {
    name: "composio-gcal",
    displayName: "Composio Google Calendar Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary: "Composio open-source connector for Google Calendar scheduling, events, and invites.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 12,
    updatedAt: NOW - 3600000 * 7,
    latestVersion: "1.0.0",
    categories: ["productivity"],
    topics: ["google-calendar", "scheduling", "google", "composio"],
    verificationTier: "structural",
    stats: { downloads: 670, installs: 220, stars: 49, versions: 2 },
  },
  {
    name: "composio-salesforce",
    displayName: "Composio Salesforce Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Salesforce CRM accounts, leads, and opportunity management.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 10,
    updatedAt: NOW - 3600000 * 10,
    latestVersion: "1.0.0",
    categories: ["crm", "sales"],
    topics: ["salesforce", "crm", "sales", "composio"],
    verificationTier: "structural",
    stats: { downloads: 490, installs: 160, stars: 34, versions: 1 },
  },
  {
    name: "composio-airtable",
    displayName: "Composio Airtable Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Airtable bases, table records, and grid automation.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 8,
    updatedAt: NOW - 3600000 * 11,
    latestVersion: "1.0.0",
    categories: ["docs", "productivity"],
    topics: ["airtable", "databases", "composio"],
    verificationTier: "structural",
    stats: { downloads: 610, installs: 195, stars: 42, versions: 2 },
  },
  {
    name: "composio-hubspot",
    displayName: "Composio HubSpot Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for HubSpot CRM contacts, deals, and marketing pipelines.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 6,
    updatedAt: NOW - 3600000 * 13,
    latestVersion: "1.0.0",
    categories: ["crm", "sales"],
    topics: ["hubspot", "crm", "marketing", "composio"],
    verificationTier: "structural",
    stats: { downloads: 430, installs: 140, stars: 31, versions: 1 },
  },
  {
    name: "composio-twitter",
    displayName: "Composio Twitter Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Twitter / X posts, thread publishing, and audience analytics.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 4,
    updatedAt: NOW - 3600000 * 3,
    latestVersion: "1.0.0",
    categories: ["social", "marketing"],
    topics: ["twitter", "social-media", "composio"],
    verificationTier: "structural",
    stats: { downloads: 780, installs: 250, stars: 58, versions: 2 },
  },
  {
    name: "composio-asana",
    displayName: "Composio Asana Connector",
    family: "connectors",
    channel: "community",
    isOfficial: true,
    summary:
      "Composio open-source connector for Asana project tasks, milestones, and team assignments.",
    ownerHandle: "composio",
    createdAt: NOW - 86400000 * 2,
    updatedAt: NOW - 3600000 * 1,
    latestVersion: "1.0.0",
    categories: ["productivity"],
    topics: ["asana", "project-management", "composio"],
    verificationTier: "structural",
    stats: { downloads: 390, installs: 125, stars: 27, versions: 1 },
  },
];
