import type { PackageListItem } from "./packageApi";

const NOW = Date.parse("2026-08-01T00:00:00.000Z");

export const OPEN_SOURCE_MCP_SERVERS: PackageListItem[] = [
  {
    name: "mcp-server-github",
    displayName: "GitHub MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Open-source Model Context Protocol server for GitHub repository search, issues, pull requests, and commit history.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 45,
    updatedAt: NOW - 3600000 * 2,
    latestVersion: "1.2.0",
    categories: ["dev", "collaboration"],
    topics: ["mcp", "github", "code-search", "pull-requests"],
    verificationTier: "structural",
    stats: { downloads: 4820, installs: 1540, stars: 340, versions: 5 },
  },
  {
    name: "mcp-server-postgres",
    displayName: "PostgreSQL MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Open-source MCP server providing PostgreSQL schema inspection, SQL query execution, and database debugging.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 40,
    updatedAt: NOW - 3600000 * 5,
    latestVersion: "1.1.0",
    categories: ["dev", "database"],
    topics: ["mcp", "postgres", "sql", "database"],
    verificationTier: "structural",
    stats: { downloads: 3120, installs: 980, stars: 210, versions: 4 },
  },
  {
    name: "mcp-server-slack",
    displayName: "Slack MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Open-source MCP server for reading Slack channels, posting messages, thread management, and channel search.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 38,
    updatedAt: NOW - 3600000 * 8,
    latestVersion: "1.0.4",
    categories: ["chat", "collaboration"],
    topics: ["mcp", "slack", "chat-ops", "messaging"],
    verificationTier: "structural",
    stats: { downloads: 2790, installs: 840, stars: 185, versions: 3 },
  },
  {
    name: "mcp-server-filesystem",
    displayName: "Filesystem MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Secure local filesystem access MCP server enabling file reads, writes, directory listing, and pattern searches.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 50,
    updatedAt: NOW - 3600000 * 1,
    latestVersion: "1.3.1",
    categories: ["system", "utility"],
    topics: ["mcp", "filesystem", "local", "files"],
    verificationTier: "structural",
    stats: { downloads: 5410, installs: 1890, stars: 420, versions: 6 },
  },
  {
    name: "mcp-server-puppeteer",
    displayName: "Puppeteer MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Browser automation MCP server for web scraping, screenshot generation, DOM interaction, and PDF exports.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 35,
    updatedAt: NOW - 3600000 * 4,
    latestVersion: "1.1.2",
    categories: ["web", "automation"],
    topics: ["mcp", "puppeteer", "browser", "scraping"],
    verificationTier: "structural",
    stats: { downloads: 3680, installs: 1120, stars: 265, versions: 4 },
  },
  {
    name: "mcp-server-everything",
    displayName: "Everything Reference MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Official reference MCP server showcasing all features: prompts, tools, resources, completions, and sampling.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 52,
    updatedAt: NOW - 3600000 * 10,
    latestVersion: "1.0.0",
    categories: ["dev", "utility"],
    topics: ["mcp", "reference", "tools", "prompts"],
    verificationTier: "structural",
    stats: { downloads: 2150, installs: 690, stars: 175, versions: 2 },
  },
  {
    name: "mcp-server-sqlite",
    displayName: "SQLite MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Lightweight database MCP server for SQL schema analysis and query execution against local SQLite .db files.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 30,
    updatedAt: NOW - 3600000 * 12,
    latestVersion: "1.0.2",
    categories: ["database", "dev"],
    topics: ["mcp", "sqlite", "database", "sql"],
    verificationTier: "structural",
    stats: { downloads: 1980, installs: 610, stars: 140, versions: 3 },
  },
  {
    name: "mcp-server-brave-search",
    displayName: "Brave Web Search MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Open-source MCP server for privacy-focused web and local business search via Brave Search API.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 28,
    updatedAt: NOW - 3600000 * 6,
    latestVersion: "1.0.5",
    categories: ["web", "utility"],
    topics: ["mcp", "brave-search", "web-search", "privacy"],
    verificationTier: "structural",
    stats: { downloads: 3100, installs: 950, stars: 230, versions: 3 },
  },
  {
    name: "mcp-server-google-maps",
    displayName: "Google Maps MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Location search, directions, place details, and geocoding MCP server for location-aware AI agents.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 25,
    updatedAt: NOW - 3600000 * 15,
    latestVersion: "1.0.1",
    categories: ["utility", "web"],
    topics: ["mcp", "google-maps", "geocoding", "places"],
    verificationTier: "structural",
    stats: { downloads: 1450, installs: 430, stars: 95, versions: 2 },
  },
  {
    name: "mcp-server-memory",
    displayName: "Knowledge Graph Memory MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Persistent graph memory MCP server providing entity, relation, and observation tracking for AI agents.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 42,
    updatedAt: NOW - 3600000 * 3,
    latestVersion: "1.1.4",
    categories: ["utility", "dev"],
    topics: ["mcp", "memory", "knowledge-graph", "context"],
    verificationTier: "structural",
    stats: { downloads: 4210, installs: 1380, stars: 310, versions: 5 },
  },
  {
    name: "mcp-server-fetch",
    displayName: "Fetch Web Scraping MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "HTTP fetch and HTML-to-markdown conversion server optimized for supplying LLMs with clean web page contents.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 48,
    updatedAt: NOW - 3600000 * 7,
    latestVersion: "1.2.1",
    categories: ["web", "utility"],
    topics: ["mcp", "fetch", "markdown", "web"],
    verificationTier: "structural",
    stats: { downloads: 4890, installs: 1560, stars: 380, versions: 4 },
  },
  {
    name: "mcp-server-sentry",
    displayName: "Sentry Error Tracking MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Sentry issue retrieval, error stack trace analysis, and release tracking MCP server for software debugging.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 20,
    updatedAt: NOW - 3600000 * 9,
    latestVersion: "1.0.0",
    categories: ["dev", "utility"],
    topics: ["mcp", "sentry", "debugging", "errors"],
    verificationTier: "structural",
    stats: { downloads: 1220, installs: 380, stars: 88, versions: 1 },
  },
  {
    name: "mcp-server-obsidian",
    displayName: "Obsidian Vault MCP Server",
    family: "mcp",
    channel: "community",
    isOfficial: true,
    summary:
      "Open-source MCP server for searching, reading, and editing notes inside local Obsidian markdown vaults.",
    ownerHandle: "modelcontextprotocol",
    createdAt: NOW - 86400000 * 18,
    updatedAt: NOW - 3600000 * 11,
    latestVersion: "1.0.3",
    categories: ["docs", "productivity"],
    topics: ["mcp", "obsidian", "notes", "markdown"],
    verificationTier: "structural",
    stats: { downloads: 1850, installs: 590, stars: 165, versions: 3 },
  },
];
