/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishSkillRouteImport } from './routes/publish-skill'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountBannedRouteImport } from './routes/account-banned'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as PublishersIndexRouteImport } from './routes/publishers/index'
import { Route as CreatorsIndexRouteImport } from './routes/creators/index'
import { Route as UserHandleRouteImport } from './routes/user/$handle'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as SkillsPublishRouteImport } from './routes/skills/publish'
import { Route as PHandleRouteImport } from './routes/p/$handle'
import { Route as OrgsHandleRouteImport } from './routes/orgs/$handle'
import { Route as CliDeviceRouteImport } from './routes/cli/device'
import { Route as CliAuthRouteImport } from './routes/cli/auth'
import { Route as AuthDocsRouteImport } from './routes/auth/docs'
import { Route as OwnerSlugRouteImport } from './routes/$owner/$slug'
import { Route as OwnerSkillsSlugRouteImport } from './routes/$owner/skills/$slug'
import { Route as OwnerSlugSettingsRouteImport } from './routes/$owner/$slug/settings'
import { Route as OwnerSlugSecurityAuditRouteImport } from './routes/$owner/$slug/security-audit'
import { Route as OwnerSkillsSlugSettingsRouteImport } from './routes/$owner/skills/$slug/settings'
import { Route as OwnerSkillsSlugSecurityAuditRouteImport } from './routes/$owner/skills/$slug/security-audit'
import { Route as OwnerSlugSecurityScannerRouteImport } from './routes/$owner/$slug/security/$scanner'
import { Route as OwnerSkillsSlugSecurityScannerRouteImport } from './routes/$owner/skills/$slug/security/$scanner'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishSkillRoute = PublishSkillRouteImport.update({
  id: '/publish-skill',
  path: '/publish-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBannedRoute = AccountBannedRouteImport.update({
  id: '/account-banned',
  path: '/account-banned',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishersIndexRoute = PublishersIndexRouteImport.update({
  id: '/publishers/',
  path: '/publishers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHandleRoute = UserHandleRouteImport.update({
  id: '/user/$handle',
  path: '/user/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsPublishRoute = SkillsPublishRouteImport.update({
  id: '/skills/publish',
  path: '/skills/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsHandleRoute = OrgsHandleRouteImport.update({
  id: '/orgs/$handle',
  path: '/orgs/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CliDeviceRoute = CliDeviceRouteImport.update({
  id: '/cli/device',
  path: '/cli/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/auth/docs',
  path: '/auth/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugRoute = OwnerSlugRouteImport.update({
  id: '/$owner/$slug',
  path: '/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSkillsSlugRoute = OwnerSkillsSlugRouteImport.update({
  id: '/$owner/skills/$slug',
  path: '/$owner/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugSettingsRoute = OwnerSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerSlugRoute,
} as any)
const OwnerSlugSecurityAuditRoute = OwnerSlugSecurityAuditRouteImport.update({
  id: '/security-audit',
  path: '/security-audit',
  getParentRoute: () => OwnerSlugRoute,
} as any)
const OwnerSkillsSlugSettingsRoute = OwnerSkillsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerSkillsSlugRoute,
} as any)
const OwnerSkillsSlugSecurityAuditRoute =
  OwnerSkillsSlugSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => OwnerSkillsSlugRoute,
  } as any)
const OwnerSlugSecurityScannerRoute =
  OwnerSlugSecurityScannerRouteImport.update({
    id: '/security/$scanner',
    path: '/security/$scanner',
    getParentRoute: () => OwnerSlugRoute,
  } as any)
const OwnerSkillsSlugSecurityScannerRoute =
  OwnerSkillsSlugSecurityScannerRouteImport.update({
    id: '/security/$scanner',
    path: '/security/$scanner',
    getParentRoute: () => OwnerSkillsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/auth/docs': typeof AuthDocsRoute
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/creators/': typeof CreatorsIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/$owner/skills/$slug': typeof OwnerSkillsSlugRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/$owner/skills/$slug/security-audit': typeof OwnerSkillsSlugSecurityAuditRoute
  '/$owner/skills/$slug/settings': typeof OwnerSkillsSlugSettingsRoute
  '/$owner/skills/$slug/security/$scanner': typeof OwnerSkillsSlugSecurityScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/auth/docs': typeof AuthDocsRoute
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/creators': typeof CreatorsIndexRoute
  '/publishers': typeof PublishersIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/users': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/$owner/skills/$slug': typeof OwnerSkillsSlugRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/$owner/skills/$slug/security-audit': typeof OwnerSkillsSlugSecurityAuditRoute
  '/$owner/skills/$slug/settings': typeof OwnerSkillsSlugSettingsRoute
  '/$owner/skills/$slug/security/$scanner': typeof OwnerSkillsSlugSecurityScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/auth/docs': typeof AuthDocsRoute
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/creators/': typeof CreatorsIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/$owner/skills/$slug': typeof OwnerSkillsSlugRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/$owner/skills/$slug/security-audit': typeof OwnerSkillsSlugSecurityAuditRoute
  '/$owner/skills/$slug/settings': typeof OwnerSkillsSlugSettingsRoute
  '/$owner/skills/$slug/security/$scanner': typeof OwnerSkillsSlugSecurityScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/auth/docs'
    | '/cli/auth'
    | '/cli/device'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/skills/publish'
    | '/u/$handle'
    | '/user/$handle'
    | '/creators/'
    | '/publishers/'
    | '/skills/'
    | '/users/'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/$owner/skills/$slug'
    | '/$owner/$slug/security/$scanner'
    | '/$owner/skills/$slug/security-audit'
    | '/$owner/skills/$slug/settings'
    | '/$owner/skills/$slug/security/$scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/auth/docs'
    | '/cli/auth'
    | '/cli/device'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/skills/publish'
    | '/u/$handle'
    | '/user/$handle'
    | '/creators'
    | '/publishers'
    | '/skills'
    | '/users'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/$owner/skills/$slug'
    | '/$owner/$slug/security/$scanner'
    | '/$owner/skills/$slug/security-audit'
    | '/$owner/skills/$slug/settings'
    | '/$owner/skills/$slug/security/$scanner'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/auth/docs'
    | '/cli/auth'
    | '/cli/device'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/skills/publish'
    | '/u/$handle'
    | '/user/$handle'
    | '/creators/'
    | '/publishers/'
    | '/skills/'
    | '/users/'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/$owner/skills/$slug'
    | '/$owner/$slug/security/$scanner'
    | '/$owner/skills/$slug/security-audit'
    | '/$owner/skills/$slug/settings'
    | '/$owner/skills/$slug/security/$scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AccountBannedRoute: typeof AccountBannedRoute
  AdminRoute: typeof AdminRoute
  AuditsRoute: typeof AuditsRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  PublishSkillRoute: typeof PublishSkillRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  UploadRoute: typeof UploadRoute
  OwnerSlugRoute: typeof OwnerSlugRouteWithChildren
  AuthDocsRoute: typeof AuthDocsRoute
  CliAuthRoute: typeof CliAuthRoute
  CliDeviceRoute: typeof CliDeviceRoute
  OrgsHandleRoute: typeof OrgsHandleRoute
  PHandleRoute: typeof PHandleRoute
  SkillsPublishRoute: typeof SkillsPublishRoute
  UHandleRoute: typeof UHandleRoute
  UserHandleRoute: typeof UserHandleRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
  PublishersIndexRoute: typeof PublishersIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  OwnerSkillsSlugRoute: typeof OwnerSkillsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-skill': {
      id: '/publish-skill'
      path: '/publish-skill'
      fullPath: '/publish-skill'
      preLoaderRoute: typeof PublishSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-banned': {
      id: '/account-banned'
      path: '/account-banned'
      fullPath: '/account-banned'
      preLoaderRoute: typeof AccountBannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers/': {
      id: '/publishers/'
      path: '/publishers'
      fullPath: '/publishers/'
      preLoaderRoute: typeof PublishersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$handle': {
      id: '/user/$handle'
      path: '/user/$handle'
      fullPath: '/user/$handle'
      preLoaderRoute: typeof UserHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/publish': {
      id: '/skills/publish'
      path: '/skills/publish'
      fullPath: '/skills/publish'
      preLoaderRoute: typeof SkillsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$handle': {
      id: '/orgs/$handle'
      path: '/orgs/$handle'
      fullPath: '/orgs/$handle'
      preLoaderRoute: typeof OrgsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/device': {
      id: '/cli/device'
      path: '/cli/device'
      fullPath: '/cli/device'
      preLoaderRoute: typeof CliDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/docs': {
      id: '/auth/docs'
      path: '/auth/docs'
      fullPath: '/auth/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug': {
      id: '/$owner/$slug'
      path: '/$owner/$slug'
      fullPath: '/$owner/$slug'
      preLoaderRoute: typeof OwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/skills/$slug': {
      id: '/$owner/skills/$slug'
      path: '/$owner/skills/$slug'
      fullPath: '/$owner/skills/$slug'
      preLoaderRoute: typeof OwnerSkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug/settings': {
      id: '/$owner/$slug/settings'
      path: '/settings'
      fullPath: '/$owner/$slug/settings'
      preLoaderRoute: typeof OwnerSlugSettingsRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/$owner/$slug/security-audit': {
      id: '/$owner/$slug/security-audit'
      path: '/security-audit'
      fullPath: '/$owner/$slug/security-audit'
      preLoaderRoute: typeof OwnerSlugSecurityAuditRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/$owner/skills/$slug/settings': {
      id: '/$owner/skills/$slug/settings'
      path: '/settings'
      fullPath: '/$owner/skills/$slug/settings'
      preLoaderRoute: typeof OwnerSkillsSlugSettingsRouteImport
      parentRoute: typeof OwnerSkillsSlugRoute
    }
    '/$owner/skills/$slug/security-audit': {
      id: '/$owner/skills/$slug/security-audit'
      path: '/security-audit'
      fullPath: '/$owner/skills/$slug/security-audit'
      preLoaderRoute: typeof OwnerSkillsSlugSecurityAuditRouteImport
      parentRoute: typeof OwnerSkillsSlugRoute
    }
    '/$owner/$slug/security/$scanner': {
      id: '/$owner/$slug/security/$scanner'
      path: '/security/$scanner'
      fullPath: '/$owner/$slug/security/$scanner'
      preLoaderRoute: typeof OwnerSlugSecurityScannerRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/$owner/skills/$slug/security/$scanner': {
      id: '/$owner/skills/$slug/security/$scanner'
      path: '/security/$scanner'
      fullPath: '/$owner/skills/$slug/security/$scanner'
      preLoaderRoute: typeof OwnerSkillsSlugSecurityScannerRouteImport
      parentRoute: typeof OwnerSkillsSlugRoute
    }
  }
}

interface OwnerSlugRouteChildren {
  OwnerSlugSecurityAuditRoute: typeof OwnerSlugSecurityAuditRoute
  OwnerSlugSettingsRoute: typeof OwnerSlugSettingsRoute
  OwnerSlugSecurityScannerRoute: typeof OwnerSlugSecurityScannerRoute
}

const OwnerSlugRouteChildren: OwnerSlugRouteChildren = {
  OwnerSlugSecurityAuditRoute: OwnerSlugSecurityAuditRoute,
  OwnerSlugSettingsRoute: OwnerSlugSettingsRoute,
  OwnerSlugSecurityScannerRoute: OwnerSlugSecurityScannerRoute,
}

const OwnerSlugRouteWithChildren = OwnerSlugRoute._addFileChildren(
  OwnerSlugRouteChildren,
)

interface OwnerSkillsSlugRouteChildren {
  OwnerSkillsSlugSecurityAuditRoute: typeof OwnerSkillsSlugSecurityAuditRoute
  OwnerSkillsSlugSettingsRoute: typeof OwnerSkillsSlugSettingsRoute
  OwnerSkillsSlugSecurityScannerRoute: typeof OwnerSkillsSlugSecurityScannerRoute
}

const OwnerSkillsSlugRouteChildren: OwnerSkillsSlugRouteChildren = {
  OwnerSkillsSlugSecurityAuditRoute: OwnerSkillsSlugSecurityAuditRoute,
  OwnerSkillsSlugSettingsRoute: OwnerSkillsSlugSettingsRoute,
  OwnerSkillsSlugSecurityScannerRoute: OwnerSkillsSlugSecurityScannerRoute,
}

const OwnerSkillsSlugRouteWithChildren = OwnerSkillsSlugRoute._addFileChildren(
  OwnerSkillsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AccountBannedRoute: AccountBannedRoute,
  AdminRoute: AdminRoute,
  AuditsRoute: AuditsRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  PublishSkillRoute: PublishSkillRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  UploadRoute: UploadRoute,
  OwnerSlugRoute: OwnerSlugRouteWithChildren,
  AuthDocsRoute: AuthDocsRoute,
  CliAuthRoute: CliAuthRoute,
  CliDeviceRoute: CliDeviceRoute,
  OrgsHandleRoute: OrgsHandleRoute,
  PHandleRoute: PHandleRoute,
  SkillsPublishRoute: SkillsPublishRoute,
  UHandleRoute: UHandleRoute,
  UserHandleRoute: UserHandleRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
  PublishersIndexRoute: PublishersIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  OwnerSkillsSlugRoute: OwnerSkillsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
