/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors/index'
import { Route as ConnectorsSlugRouteImport } from './routes/connectors/$slug'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as GraphsSlugRouteImport } from './routes/graphs/$slug'
import { Route as LoopsSlugRouteImport } from './routes/loops/$slug'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as McpSlugRouteImport } from './routes/mcp/$slug'
import { Route as PersonaIndexRouteImport } from './routes/persona/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as PluginsCatalogSlugRouteImport } from './routes/plugins/catalog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsSlugRoute = ConnectorsSlugRouteImport.update({
  id: '/connectors/$slug',
  path: '/connectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsSlugRoute = GraphsSlugRouteImport.update({
  id: '/graphs/$slug',
  path: '/graphs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsSlugRoute = LoopsSlugRouteImport.update({
  id: '/loops/$slug',
  path: '/loops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSlugRoute = McpSlugRouteImport.update({
  id: '/mcp/$slug',
  path: '/mcp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIndexRoute = PersonaIndexRouteImport.update({
  id: '/persona/',
  path: '/persona/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsCatalogSlugRoute = PluginsCatalogSlugRouteImport.update({
  id: '/plugins/catalog/$slug',
  path: '/plugins/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/connectors/$slug': typeof ConnectorsSlugRoute
  '/graphs/$slug': typeof GraphsSlugRoute
  '/loops/$slug': typeof LoopsSlugRoute
  '/mcp/$slug': typeof McpSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/plugins/catalog/$slug': typeof PluginsCatalogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/connectors/$slug': typeof ConnectorsSlugRoute
  '/graphs/$slug': typeof GraphsSlugRoute
  '/loops/$slug': typeof LoopsSlugRoute
  '/mcp/$slug': typeof McpSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/flows': typeof FlowsIndexRoute
  '/mcp': typeof McpIndexRoute
  '/persona': typeof PersonaIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/plugins/catalog/$slug': typeof PluginsCatalogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/connectors/$slug': typeof ConnectorsSlugRoute
  '/graphs/$slug': typeof GraphsSlugRoute
  '/loops/$slug': typeof LoopsSlugRoute
  '/mcp/$slug': typeof McpSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/flows/': typeof FlowsIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/plugins/catalog/$slug': typeof PluginsCatalogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/connectors/$slug'
    | '/graphs/$slug'
    | '/loops/$slug'
    | '/mcp/$slug'
    | '/skills/$slug'
    | '/connectors/'
    | '/flows/'
    | '/mcp/'
    | '/persona/'
    | '/plugins/'
    | '/skills/'
    | '/plugins/catalog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/connectors/$slug'
    | '/graphs/$slug'
    | '/loops/$slug'
    | '/mcp/$slug'
    | '/skills/$slug'
    | '/connectors'
    | '/flows'
    | '/mcp'
    | '/persona'
    | '/plugins'
    | '/skills'
    | '/plugins/catalog/$slug'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/connectors/$slug'
    | '/graphs/$slug'
    | '/loops/$slug'
    | '/mcp/$slug'
    | '/skills/$slug'
    | '/connectors/'
    | '/flows/'
    | '/mcp/'
    | '/persona/'
    | '/plugins/'
    | '/skills/'
    | '/plugins/catalog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ConnectorsSlugRoute: typeof ConnectorsSlugRoute
  GraphsSlugRoute: typeof GraphsSlugRoute
  LoopsSlugRoute: typeof LoopsSlugRoute
  McpSlugRoute: typeof McpSlugRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
  McpIndexRoute: typeof McpIndexRoute
  PersonaIndexRoute: typeof PersonaIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  PluginsCatalogSlugRoute: typeof PluginsCatalogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$slug': {
      id: '/connectors/$slug'
      path: '/connectors/$slug'
      fullPath: '/connectors/$slug'
      preLoaderRoute: typeof ConnectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$slug': {
      id: '/graphs/$slug'
      path: '/graphs/$slug'
      fullPath: '/graphs/$slug'
      preLoaderRoute: typeof GraphsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops/$slug': {
      id: '/loops/$slug'
      path: '/loops/$slug'
      fullPath: '/loops/$slug'
      preLoaderRoute: typeof LoopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$slug': {
      id: '/mcp/$slug'
      path: '/mcp/$slug'
      fullPath: '/mcp/$slug'
      preLoaderRoute: typeof McpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/': {
      id: '/persona/'
      path: '/persona'
      fullPath: '/persona/'
      preLoaderRoute: typeof PersonaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/catalog/$slug': {
      id: '/plugins/catalog/$slug'
      path: '/plugins/catalog/$slug'
      fullPath: '/plugins/catalog/$slug'
      preLoaderRoute: typeof PluginsCatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ConnectorsSlugRoute: ConnectorsSlugRoute,
  GraphsSlugRoute: GraphsSlugRoute,
  LoopsSlugRoute: LoopsSlugRoute,
  McpSlugRoute: McpSlugRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  McpIndexRoute: McpIndexRoute,
  PersonaIndexRoute: PersonaIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  PluginsCatalogSlugRoute: PluginsCatalogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
